### ISSUE TITLE
skmp's TODO

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#94]
- [x] Implement block lookups to not be hacky / aliasy
- [x] Syscall unit tests #116
- [x] Look into signals / marshaling -> at least for segfaults with host context #90
-- Write some test cases, exit on loops, etc
- [x] Cleanup the op dispatcher #26 
- [x] Build chroot image without x87 love
